import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { industries, getIndustry } from "../../../../data/industries";
import { SITE_URL, jsonLdGraph, webPageSchema, breadcrumbSchema, faqPageSchema } from "../../../lib/structured-data";
import JsonLd from "../../../components/JsonLd";
import { FAQItem } from "../../faq/FAQItem";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return industries.map((i) => ({ slug: i.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const industry = getIndustry(slug);
  if (!industry) return {};
  const url = `https://www.waypointfranchise.com/industries/${slug}`;
  return {
    title: `${industry.metaTitle} | Waypoint Franchise Advisors`,
    description: industry.metaDescription,
    alternates: {
      canonical: url,
      types: { "text/markdown": `${url}.md` },
    },
    openGraph: {
      title: `${industry.name} Franchises | Waypoint Franchise Advisors`,
      description: industry.metaDescription,
      url,
      // og:image is generated by the colocated opengraph-image.tsx (next/og).
    },
  };
}

export default async function IndustryPage({ params }: Props) {
  const { slug } = await params;
  const industry = getIndustry(slug);
  if (!industry) notFound();

  const pageUrl = `${SITE_URL}/industries/${slug}`;
  const faqSchema = faqPageSchema(industry.faqs, pageUrl);

  return (
    <main className="bg-[#FAF8F4] text-[#0c1929]">
      <JsonLd
        data={jsonLdGraph(
          webPageSchema({
            url: pageUrl,
            name: `${industry.name} Franchises | Waypoint Franchise Advisors`,
            description: industry.metaDescription,
            breadcrumb: breadcrumbSchema([
              { name: "Home", url: SITE_URL },
              { name: "Industries", url: `${SITE_URL}/industries` },
              { name: industry.name, url: pageUrl },
            ]),
          }),
          faqSchema,
        )}
      />

      {/* Hero */}
      <section className="pt-20 sm:pt-28 pb-12 sm:pb-16 px-6 border-b border-[#e8e0d0]">
        <div className="max-w-4xl mx-auto">
          <Link href="/industries" className="inline-flex items-center text-xs text-[#8E3012] tracking-wide uppercase font-medium hover:text-[#CC6535] transition-colors mb-8">
            ← All categories
          </Link>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">
            Category Guide
          </p>
          <h1 className="font-playfair text-4xl sm:text-5xl text-[#0c1929] leading-tight mb-6 max-w-3xl">
            {industry.name} franchises
          </h1>
          <p className="text-base sm:text-lg text-[#4a4a3e] leading-relaxed max-w-2xl mb-4">
            {industry.heroTagline}
          </p>
          <p className="text-base text-[#4a4a3e] leading-relaxed max-w-2xl">
            {industry.intro}
          </p>
          <Link
            href={`/industries/${slug}/cost`}
            className="inline-flex items-center text-sm font-medium text-[#8E3012] hover:text-[#CC6535] transition-colors mt-6"
          >
            How much does a {industry.name.toLowerCase()} franchise cost? →
          </Link>
        </div>
      </section>

      {/* What it is / Who it fits / Watch for */}
      <section className="max-w-4xl mx-auto px-6 py-14 sm:py-20 grid gap-10 sm:grid-cols-3">
        <div>
          <h2 className="font-playfair text-xl text-[#0c1929] mb-3">What it actually is</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{industry.whatItIs}</p>
        </div>
        <div>
          <h2 className="font-playfair text-xl text-[#0c1929] mb-3">Who it tends to fit</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{industry.whoItFits}</p>
        </div>
        <div>
          <h2 className="font-playfair text-xl text-[#8a4a20] mb-3">What to watch for</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{industry.watchFor}</p>
        </div>
      </section>

      {/* Checklist callout — category-specific checklist when one exists, else the
          universal franchise readiness checklist. */}
      <section className="bg-[#0c1929] py-12 px-6">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-start sm:items-center gap-6">
          <div className="flex-1">
            <p className="text-xs font-semibold tracking-widest text-[#CC6535] uppercase mb-1">Free Download</p>
            <p className="font-playfair text-xl text-white mb-1">
              {industry.checklistSlug
                ? `The ${industry.name} Franchise Checklist`
                : "The Franchise Readiness Checklist"}
            </p>
            <p className="text-sm text-white/70 leading-relaxed">
              {industry.checklistSlug
                ? `A structured framework for evaluating ${industry.name.toLowerCase()} concepts — the questions to ask and the items to verify before you commit.`
                : `A structured framework for evaluating any franchise — the questions to ask and the items to verify before you commit, applied to ${industry.name.toLowerCase()} concepts.`}
            </p>
          </div>
          <Link
            href={industry.checklistSlug ? `/checklists#checklist-${industry.checklistSlug}` : "/checklists#checklist-universal"}
            className="shrink-0 inline-flex items-center justify-center px-6 py-3 text-sm font-semibold text-[#0c1929] bg-[#CC6535] hover:bg-[#D4724A] rounded-lg transition-all min-h-[44px] whitespace-nowrap"
          >
            Get the Checklist →
          </Link>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-3xl mx-auto px-6 py-14 sm:py-20">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">
          Common Questions
        </p>
        <h2 className="font-playfair text-2xl sm:text-3xl mb-8">
          Questions about {industry.name.toLowerCase()} franchises
        </h2>
        <div>
          {industry.faqs.map(({ q, a }) => (
            <FAQItem key={q} q={q} a={a} />
          ))}
        </div>
      </section>

      {/* Related articles */}
      {industry.relatedArticles.length > 0 && (
        <section className="max-w-4xl mx-auto px-6 pb-16 sm:pb-20 border-t border-[#e8e0d0] pt-12">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-8 h-[2px] bg-[#CC6535]" />
            <p className="text-xs font-medium text-[#CC6535] uppercase tracking-[0.2em]">Go Deeper</p>
          </div>
          <div className="grid gap-5 sm:grid-cols-2">
            {industry.relatedArticles.map((a) => (
              <Link
                key={a.slug}
                href={`/resources/${a.slug}`}
                className="group block bg-white border border-[#e8e0d0] rounded-lg p-5 hover:shadow-md hover:border-[#CC6535]/40 transition-all"
              >
                <div className="w-5 h-[2px] bg-[#CC6535] mb-3 group-hover:w-8 transition-all duration-300" />
                <h3 className="font-playfair text-[0.95rem] leading-snug text-[#0c1929] group-hover:text-[#8E3012] transition-colors mb-3">
                  {a.title}
                </h3>
                <p className="text-xs text-[#8E3012] font-medium tracking-wide">Read →</p>
              </Link>
            ))}
          </div>
        </section>
      )}

      {/* CTA */}
      <section className="bg-[#0c1929] py-14 px-6 text-center">
        <p className="font-playfair text-2xl text-white mb-4">
          Curious whether {industry.name.toLowerCase()} is right for you?
        </p>
        <p className="text-white/70 mb-8 max-w-sm mx-auto text-sm leading-relaxed">
          Thirty minutes. No pitch. We will talk through whether this category fits your goals, capital, and life.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link
            href="/book"
            className="inline-flex items-center justify-center px-8 py-4 text-sm font-semibold tracking-wide text-[#0c1929] bg-[#CC6535] hover:bg-[#D4724A] rounded-lg transition-all min-h-[48px]"
          >
            Book a Free Call
          </Link>
          <a
            href="sms:+12149951062"
            className="inline-flex items-center justify-center gap-1.5 px-8 py-4 text-sm font-semibold tracking-wide text-white border border-white/25 hover:bg-white/10 rounded-lg transition-all min-h-[48px]"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg>
            Text Me
          </a>
        </div>
      </section>
    </main>
  );
}
