import type { Metadata } from "next";
import Link from "next/link";
import { industries } from "../../../data/industries";
import { SITE_URL, jsonLdGraph, collectionPageSchema, breadcrumbSchema } from "../../lib/structured-data";
import JsonLd from "../../components/JsonLd";

export const metadata: Metadata = {
  title: "Franchise Industries & Categories",
  description:
    "Explore the major franchise categories: home services, senior care, fitness & wellness, food & beverage, and B2B services. What each is really like, who it fits, and the tradeoffs.",
  alternates: {
    canonical: "https://www.waypointfranchise.com/industries",
    types: { "text/markdown": "https://www.waypointfranchise.com/industries.md" },
  },
  openGraph: {
    title: "Franchise Industries & Categories | Waypoint Franchise Advisors",
    description:
      "Honest, category-by-category guides to the main types of franchise: what each is really like, who it fits, and what to watch for.",
    url: "https://www.waypointfranchise.com/industries",
    // og:image is generated by the colocated opengraph-image.tsx (next/og).
  },
};

export default function IndustriesPage() {
  return (
    <main className="bg-[#FAF8F4] text-[#0c1929]">
      <JsonLd
        data={jsonLdGraph(
          collectionPageSchema({
            url: `${SITE_URL}/industries`,
            name: "Franchise Industries & Categories | Waypoint Franchise Advisors",
            description:
              "Explore the major franchise categories: home services, senior care, fitness & wellness, food & beverage, and B2B services. What each is really like, who it fits, and the tradeoffs.",
            breadcrumb: breadcrumbSchema([
              { name: "Home", url: SITE_URL },
              { name: "Industries", url: `${SITE_URL}/industries` },
            ]),
            items: industries.map((i) => ({
              name: i.name,
              url: `${SITE_URL}/industries/${i.slug}`,
            })),
          }),
        )}
      />

      {/* Hero */}
      <section className="pt-20 sm:pt-28 pb-12 sm:pb-16 px-6 border-b border-[#e8e0d0]">
        <div className="max-w-4xl mx-auto">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">
            Franchise Categories
          </p>
          <h1 className="font-playfair text-4xl sm:text-5xl text-[#0c1929] leading-tight mb-6 max-w-3xl">
            The major franchise categories, explained honestly
          </h1>
          <p className="text-base sm:text-lg text-[#4a4a3e] leading-relaxed max-w-2xl">
            Every category has a different shape: different capital, different daily reality, different kind of owner it suits. These guides cover what each one is actually like, who tends to thrive in it, and the tradeoffs worth weighing before you fall for a logo.
          </p>
        </div>
      </section>

      {/* Category grid */}
      <section className="max-w-4xl mx-auto px-6 py-14 sm:py-20">
        <div className="grid gap-5 sm:grid-cols-2">
          {industries.map((i) => (
            <Link
              key={i.slug}
              href={`/industries/${i.slug}`}
              className="group block bg-white border border-[#e8e0d0] rounded-xl p-6 hover:shadow-md hover:border-[#CC6535]/40 transition-all"
            >
              <div className="w-5 h-[2px] bg-[#CC6535] mb-4 group-hover:w-8 transition-all duration-300" />
              <h2 className="font-playfair text-xl text-[#0c1929] group-hover:text-[#8E3012] transition-colors mb-2">
                {i.name}
              </h2>
              <p className="text-sm text-[#5a5a4a] leading-relaxed mb-4">{i.heroTagline}</p>
              <p className="text-xs text-[#8E3012] font-medium tracking-wide">Explore the category →</p>
            </Link>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#0c1929] py-14 px-6 text-center">
        <p className="font-playfair text-2xl text-white mb-4">Not sure which category fits you?</p>
        <p className="text-white/70 mb-8 max-w-sm mx-auto text-sm leading-relaxed">
          Take the archetype quiz to see which categories match your working style, or just book a call and talk it through.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link
            href="/archetype"
            className="inline-flex items-center justify-center px-8 py-4 text-sm font-semibold tracking-wide text-[#0c1929] bg-[#CC6535] hover:bg-[#D4724A] rounded-lg transition-all min-h-[48px]"
          >
            Take the Quiz
          </Link>
          <Link
            href="/book"
            className="inline-flex items-center justify-center px-8 py-4 text-sm font-semibold tracking-wide text-white border border-white/25 hover:bg-white/10 rounded-lg transition-all min-h-[48px]"
          >
            Book a Free Call
          </Link>
        </div>
      </section>
    </main>
  );
}
