import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { industries, getIndustry, getIndustryCost } from "../../../../../data/industries";
import { SITE_URL, jsonLdGraph, webPageSchema, breadcrumbSchema, faqPageSchema } from "../../../../lib/structured-data";
import JsonLd from "../../../../components/JsonLd";
import { FAQItem } from "../../../faq/FAQItem";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  // Only categories that have cost content get a /cost page.
  return industries.filter((i) => getIndustryCost(i.slug)).map((i) => ({ slug: i.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const industry = getIndustry(slug);
  const cost = getIndustryCost(slug);
  if (!industry || !cost) return {};
  const url = `https://www.waypointfranchise.com/industries/${slug}/cost`;
  const lower = industry.name.toLowerCase();
  return {
    title: `How Much Does a ${industry.name} Franchise Cost?`,
    description: `What a ${lower} franchise actually costs: the typical investment range, what drives the cost, and the components to budget for. Educational ranges only; the brand-specific figure is in FDD Item 7.`,
    alternates: { canonical: url, types: { "text/markdown": `${url}.md` } },
    openGraph: {
      title: `How Much Does a ${industry.name} Franchise Cost?`,
      description: `The typical investment range for ${lower} franchises, what drives it, and what to budget for.`,
      url,
      // og:image is generated by the colocated opengraph-image.tsx (next/og).
    },
  };
}

export default async function IndustryCostPage({ params }: Props) {
  const { slug } = await params;
  const industry = getIndustry(slug);
  const cost = getIndustryCost(slug);
  if (!industry || !cost) notFound();

  const pageUrl = `${SITE_URL}/industries/${slug}/cost`;
  const lower = industry.name.toLowerCase();

  return (
    <main className="bg-[#FAF8F4] text-[#0c1929]">
      <JsonLd
        data={jsonLdGraph(
          webPageSchema({
            url: pageUrl,
            name: `How Much Does a ${industry.name} Franchise Cost? | Waypoint Franchise Advisors`,
            description: `What a ${lower} franchise actually costs: the typical investment range, what drives the cost, and the components to budget for.`,
            breadcrumb: breadcrumbSchema([
              { name: "Home", url: SITE_URL },
              { name: "Industries", url: `${SITE_URL}/industries` },
              { name: industry.name, url: `${SITE_URL}/industries/${slug}` },
              { name: "Cost", url: pageUrl },
            ]),
          }),
          faqPageSchema(cost.faqs, pageUrl),
        )}
      />

      {/* Hero */}
      <section className="pt-20 sm:pt-28 pb-12 sm:pb-16 px-6 border-b border-[#e8e0d0]">
        <div className="max-w-4xl mx-auto">
          <Link href={`/industries/${slug}`} className="inline-flex items-center text-xs text-[#8E3012] tracking-wide uppercase font-medium hover:text-[#CC6535] transition-colors mb-8">
            ← {industry.name} franchises
          </Link>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">Cost Guide</p>
          <h1 className="font-playfair text-4xl sm:text-5xl text-[#0c1929] leading-tight mb-6 max-w-3xl">
            How much does a {lower} franchise cost?
          </h1>
          <p className="text-base sm:text-lg text-[#4a4a3e] leading-relaxed max-w-2xl">{cost.band}</p>
        </div>
      </section>

      {/* Drivers + components */}
      <section className="max-w-4xl mx-auto px-6 py-14 sm:py-20 grid gap-10 sm:grid-cols-2">
        <div>
          <h2 className="font-playfair text-xl text-[#0c1929] mb-3">What drives the cost</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{cost.drivers}</p>
        </div>
        <div>
          <h2 className="font-playfair text-xl text-[#0c1929] mb-3">What you are budgeting for</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{cost.components}</p>
        </div>
      </section>

      {/* FDD note */}
      <section className="bg-[#0c1929] py-12 px-6">
        <div className="max-w-4xl mx-auto">
          <p className="text-xs font-semibold tracking-widest text-[#CC6535] uppercase mb-2">A Note on Numbers</p>
          <p className="text-sm text-white/75 leading-relaxed max-w-3xl">
            The ranges above are general, educational, and not a quote. Every franchisor publishes its exact estimated initial investment in Item 7 of its Franchise Disclosure Document, and your real cost depends on the specific brand, your market, and your build-out. Funding can cover much of it. See how franchises are typically financed.
          </p>
          <Link href="/franchise-financing" className="inline-flex items-center text-[#CC6535] text-sm font-medium hover:text-[#D4724A] transition-colors mt-4">
            How to finance a franchise →
          </Link>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-3xl mx-auto px-6 py-14 sm:py-20">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">Common Questions</p>
        <h2 className="font-playfair text-2xl sm:text-3xl mb-8">Questions about {lower} franchise cost</h2>
        <div>
          {cost.faqs.map(({ q, a }) => (
            <FAQItem key={q} q={q} a={a} />
          ))}
        </div>
      </section>

      {/* Related links */}
      <section className="max-w-4xl mx-auto px-6 pb-16 sm:pb-20 border-t border-[#e8e0d0] pt-12">
        <div className="grid gap-5 sm:grid-cols-3">
          <Link href={`/industries/${slug}`} className="group block rounded-lg border border-[#e8e0d0] bg-white p-5 hover:border-[#CC6535]/40 hover:shadow-sm transition-all">
            <span className="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-[#8E3012]">Category guide</span>
            <span className="mt-1 block font-playfair text-base text-[#0c1929] group-hover:text-[#8E3012] transition-colors">{industry.name} franchises →</span>
          </Link>
          <Link href="/investment" className="group block rounded-lg border border-[#e8e0d0] bg-white p-5 hover:border-[#CC6535]/40 hover:shadow-sm transition-all">
            <span className="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-[#8E3012]">Overall</span>
            <span className="mt-1 block font-playfair text-base text-[#0c1929] group-hover:text-[#8E3012] transition-colors">What a franchise costs overall →</span>
          </Link>
          <Link href="/franchise-financing" className="group block rounded-lg border border-[#e8e0d0] bg-white p-5 hover:border-[#CC6535]/40 hover:shadow-sm transition-all">
            <span className="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-[#8E3012]">Funding</span>
            <span className="mt-1 block font-playfair text-base text-[#0c1929] group-hover:text-[#8E3012] transition-colors">How to finance it →</span>
          </Link>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#0c1929] py-14 px-6 text-center">
        <p className="font-playfair text-2xl text-white mb-4">Want the real number for your situation?</p>
        <p className="text-white/70 mb-8 max-w-sm mx-auto text-sm leading-relaxed">
          Thirty minutes. No pitch. We will talk through what {lower} concepts actually cost and how funding usually comes together.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link href="/book" className="inline-flex items-center justify-center px-8 py-4 text-sm font-semibold tracking-wide text-[#0c1929] bg-[#CC6535] hover:bg-[#D4724A] rounded-lg transition-all min-h-[48px]">Book a Free Call</Link>
          <a href="sms:+12149951062" className="inline-flex items-center justify-center gap-1.5 px-8 py-4 text-sm font-semibold tracking-wide text-white border border-white/25 hover:bg-white/10 rounded-lg transition-all min-h-[48px]">
            <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg>
            Text Me
          </a>
        </div>
      </section>
    </main>
  );
}
