import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { financingGuides, getFinancingGuide } from "../../../../data/financing";
import { SITE_URL, jsonLdGraph, webPageSchema, breadcrumbSchema, faqPageSchema } from "../../../lib/structured-data";
import JsonLd from "../../../components/JsonLd";
import { FAQItem } from "../../faq/FAQItem";

type Props = { params: Promise<{ method: string }> };

export function generateStaticParams() {
  return financingGuides.map((g) => ({ method: g.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { method } = await params;
  const guide = getFinancingGuide(method);
  if (!guide) return {};
  const url = `https://www.waypointfranchise.com/franchise-financing/${method}`;
  return {
    title: `${guide.metaTitle} | Waypoint Franchise Advisors`,
    description: guide.metaDescription,
    alternates: { canonical: url, types: { "text/markdown": `${url}.md` } },
    openGraph: {
      title: `${guide.name} | Waypoint Franchise Advisors`,
      description: guide.metaDescription,
      url,
      // og:image is generated by the colocated opengraph-image.tsx (next/og).
    },
  };
}

export default async function FinancingGuidePage({ params }: Props) {
  const { method } = await params;
  const guide = getFinancingGuide(method);
  if (!guide) notFound();

  const pageUrl = `${SITE_URL}/franchise-financing/${method}`;

  return (
    <main className="bg-[#FAF8F4] text-[#0c1929]">
      <JsonLd
        data={jsonLdGraph(
          webPageSchema({
            url: pageUrl,
            name: `${guide.metaTitle} | Waypoint Franchise Advisors`,
            description: guide.metaDescription,
            breadcrumb: breadcrumbSchema([
              { name: "Home", url: SITE_URL },
              { name: "Franchise Financing", url: `${SITE_URL}/franchise-financing` },
              { name: guide.name, url: pageUrl },
            ]),
          }),
          faqPageSchema(guide.faqs, pageUrl),
        )}
      />

      {/* Hero */}
      <section className="pt-20 sm:pt-28 pb-12 sm:pb-16 px-6 border-b border-[#e8e0d0]">
        <div className="max-w-4xl mx-auto">
          <Link href="/franchise-financing" className="inline-flex items-center text-xs text-[#8E3012] tracking-wide uppercase font-medium hover:text-[#CC6535] transition-colors mb-8">
            ← All financing options
          </Link>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">
            Funding Method
          </p>
          <h1 className="font-playfair text-4xl sm:text-5xl text-[#0c1929] leading-tight mb-6 max-w-3xl">
            {guide.name}
          </h1>
          <p className="text-base sm:text-lg text-[#4a4a3e] leading-relaxed max-w-2xl mb-4">
            {guide.heroTagline}
          </p>
          <p className="text-base text-[#4a4a3e] leading-relaxed max-w-2xl">{guide.intro}</p>
        </div>
      </section>

      {/* Detail blocks */}
      <section className="max-w-4xl mx-auto px-6 py-14 sm:py-20 grid gap-10 sm:grid-cols-3">
        <div>
          <h2 className="font-playfair text-xl text-[#0c1929] mb-3">How it works</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{guide.howItWorks}</p>
        </div>
        <div>
          <h2 className="font-playfair text-xl text-[#0c1929] mb-3">Who it tends to fit</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{guide.whoItFits}</p>
        </div>
        <div>
          <h2 className="font-playfair text-xl text-[#8a4a20] mb-3">What to watch for</h2>
          <p className="text-sm text-[#4a4a3e] leading-relaxed">{guide.watchFor}</p>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-3xl mx-auto px-6 pb-14 sm:pb-20">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">Common Questions</p>
        <h2 className="font-playfair text-2xl sm:text-3xl mb-8">Questions about {guide.name.toLowerCase()}</h2>
        <div>
          {guide.faqs.map(({ q, a }) => (
            <FAQItem key={q} q={q} a={a} />
          ))}
        </div>
      </section>

      {/* Up-link to pillar + related article */}
      <section className="max-w-4xl mx-auto px-6 pb-16 sm:pb-20 border-t border-[#e8e0d0] pt-12">
        <div className="grid gap-5 sm:grid-cols-2">
          <Link
            href="/franchise-financing"
            className="group block rounded-lg border border-[#e8e0d0] bg-white p-5 hover:border-[#CC6535]/40 hover:shadow-sm transition-all"
          >
            <span className="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-[#8E3012]">Part of our guide</span>
            <span className="mt-1 block font-playfair text-base text-[#0c1929] group-hover:text-[#8E3012] transition-colors">
              How to Finance a Franchise →
            </span>
          </Link>
          {guide.relatedArticleSlug && (
            <Link
              href={`/resources/${guide.relatedArticleSlug}`}
              className="group block rounded-lg border border-[#e8e0d0] bg-white p-5 hover:border-[#CC6535]/40 hover:shadow-sm transition-all"
            >
              <span className="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-[#8E3012]">Go deeper</span>
              <span className="mt-1 block font-playfair text-base text-[#0c1929] group-hover:text-[#8E3012] transition-colors">
                {guide.relatedArticleTitle} →
              </span>
            </Link>
          )}
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#0c1929] py-14 px-6 text-center">
        <p className="font-playfair text-2xl text-white mb-4">Want help mapping funding to your situation?</p>
        <p className="text-white/70 mb-8 max-w-sm mx-auto text-sm leading-relaxed">
          Thirty minutes. No pitch. We will talk through what concepts fit your capital and how funding usually comes together.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link
            href="/book"
            className="inline-flex items-center justify-center px-8 py-4 text-sm font-semibold tracking-wide text-[#0c1929] bg-[#CC6535] hover:bg-[#D4724A] rounded-lg transition-all min-h-[48px]"
          >
            Book a Free Call
          </Link>
          <a
            href="sms:+12149951062"
            className="inline-flex items-center justify-center gap-1.5 px-8 py-4 text-sm font-semibold tracking-wide text-white border border-white/25 hover:bg-white/10 rounded-lg transition-all min-h-[48px]"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg>
            Text Me
          </a>
        </div>
      </section>
    </main>
  );
}
