import type { Metadata } from "next";
import Link from "next/link";
import { SITE_URL, jsonLdGraph, webPageSchema, breadcrumbSchema, faqPageSchema } from "../../lib/structured-data";
import JsonLd from "../../components/JsonLd";
import { FAQItem } from "../faq/FAQItem";
import { financingMethods as methods, financingFaqs as faqs } from "../../../data/financing";

// The visible accordion below AND the FAQPage JSON-LD are both built from the
// shared financingFaqs array (src/data/financing.ts), so on-page content and
// structured data can never drift (a requirement for FAQ markup to stay eligible).
const faqSchema = faqPageSchema(faqs, `${SITE_URL}/franchise-financing`);

export const metadata: Metadata = {
  title: "How to Finance a Franchise: SBA, ROBS, HELOC & More",
  description:
    "How people fund a franchise: SBA 7(a) loans, ROBS 401(k) rollovers, home equity, securities-backed lines, and franchisor financing, and how to choose.",
  alternates: {
    canonical: "https://www.waypointfranchise.com/franchise-financing",
    types: { "text/markdown": "https://www.waypointfranchise.com/franchise-financing.md" },
  },
  openGraph: {
    title: "How to Finance a Franchise | Waypoint Franchise Advisors",
    description:
      "SBA loans, ROBS, HELOC, securities-backed lines, franchisor financing. A plain-English guide to the ways franchises actually get funded.",
    url: "https://www.waypointfranchise.com/franchise-financing",
    // og:image is generated by the colocated opengraph-image.tsx (next/og).
  },
};

export default function FranchiseFinancingPage() {
  return (
    <main className="bg-[#FAF8F4] text-[#0c1929]">
      <JsonLd
        data={jsonLdGraph(
          webPageSchema({
            url: `${SITE_URL}/franchise-financing`,
            name: "How to Finance a Franchise | Waypoint Franchise Advisors",
            description:
              "The main ways people fund a franchise (SBA 7(a) loans, ROBS 401(k) rollovers, home equity, securities-backed lines, and franchisor financing) and how to think about which fits your situation.",
            breadcrumb: breadcrumbSchema([
              { name: "Home", url: SITE_URL },
              { name: "Franchise Financing", url: `${SITE_URL}/franchise-financing` },
            ]),
          }),
          faqSchema,
        )}
      />

      {/* Hero */}
      <section className="pt-20 sm:pt-28 pb-12 sm:pb-16 px-6 border-b border-[#e8e0d0]">
        <div className="max-w-4xl mx-auto">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">
            Funding Guide
          </p>
          <h1 className="font-playfair text-4xl sm:text-5xl text-[#0c1929] leading-tight mb-6 max-w-3xl">
            How to finance a franchise: the real options, in plain English
          </h1>
          <p className="text-base sm:text-lg text-[#4a4a3e] leading-relaxed max-w-2xl mb-4">
            Most people do not buy a franchise entirely in cash. They combine some liquid capital with one or more financing methods. The five paths below cover how the large majority of franchises actually get funded: what each one is, who it tends to fit, and what to watch for.
          </p>
          <p className="text-base text-[#4a4a3e] leading-relaxed max-w-2xl">
            This is educational, not financial advice or a promise of approval. Eligibility depends on your situation and the specific brand. The point is to walk into a lender or advisor conversation already knowing the vocabulary.
          </p>
        </div>
      </section>

      {/* Methods table */}
      <section className="max-w-4xl mx-auto px-6 py-14 sm:py-20">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">
          The Main Paths
        </p>
        <h2 className="font-playfair text-2xl sm:text-3xl mb-10">
          Five ways franchises get funded
        </h2>

        {/* Mobile: stacked cards */}
        <div className="sm:hidden space-y-4">
          {methods.map((row, i) => (
            <div key={row.method} className={`rounded-xl p-5 border border-[#e8e0d0] ${i % 2 === 0 ? "bg-white" : "bg-[#faf8f4]"}`}>
              <p className="font-semibold text-[#0c1929] text-sm mb-1">{row.method}</p>
              {row.guideSlug && (
                <Link href={`/franchise-financing/${row.guideSlug}`} className="inline-block mb-3 text-[11px] font-medium text-[#8E3012] hover:text-[#CC6535] transition-colors">
                  Full guide →
                </Link>
              )}
              <p className="text-[10px] font-semibold uppercase tracking-wider text-[#1b3a5f] mb-1">How it works</p>
              <p className="text-xs text-[#3a3a2e] leading-relaxed mb-3">{row.how}</p>
              <p className="text-[10px] font-semibold uppercase tracking-wider text-[#1b3a5f] mb-1">Best for</p>
              <p className="text-xs text-[#3a3a2e] leading-relaxed mb-3">{row.bestFor}</p>
              <p className="text-[10px] font-semibold uppercase tracking-wider text-[#8a4a20] mb-1">Watch for</p>
              <p className="text-xs text-[#3a3a2e] leading-relaxed">{row.watch}</p>
            </div>
          ))}
        </div>

        {/* Desktop: table */}
        <div className="hidden sm:block overflow-x-auto">
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="border-b-2 border-[#8E3012]">
                <th className="text-left py-3 pl-4 pr-6 font-semibold text-[#1b3a5f] uppercase tracking-wider text-xs w-[22%]">Method</th>
                <th className="text-left py-3 pl-4 pr-6 font-semibold text-[#1b3a5f] uppercase tracking-wider text-xs w-[33%]">How it works</th>
                <th className="text-left py-3 pl-4 pr-6 font-semibold text-[#1b3a5f] uppercase tracking-wider text-xs w-[24%]">Best for</th>
                <th className="text-left py-3 pl-4 pr-4 font-semibold text-[#8a4a20] uppercase tracking-wider text-xs w-[21%]">Watch for</th>
              </tr>
            </thead>
            <tbody>
              {methods.map((row, i) => (
                <tr key={row.method} className={`border-b border-[#e8e0d0] ${i % 2 === 0 ? "bg-white" : "bg-[#faf8f4]"}`}>
                  <td className="py-4 pl-4 pr-6 font-medium text-[#0c1929] align-top">
                    {row.method}
                    {row.guideSlug && (
                      <Link href={`/franchise-financing/${row.guideSlug}`} className="mt-1 block text-[11px] font-medium text-[#8E3012] hover:text-[#CC6535] transition-colors">
                        Full guide →
                      </Link>
                    )}
                  </td>
                  <td className="py-4 pl-4 pr-6 text-[#3a3a2e] leading-relaxed align-top">{row.how}</td>
                  <td className="py-4 pl-4 pr-6 text-[#3a3a2e] leading-relaxed align-top">{row.bestFor}</td>
                  <td className="py-4 pl-4 pr-4 text-[#3a3a2e] leading-relaxed align-top">{row.watch}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Key insight sections */}
      <section className="bg-[#0c1929] py-14 sm:py-20 px-6">
        <div className="max-w-4xl mx-auto grid sm:grid-cols-2 gap-8">
          <div>
            <h2 className="font-playfair text-2xl text-white mb-4">
              Most deals blend more than one source
            </h2>
            <p className="text-white/70 text-sm leading-relaxed mb-4">
              It is common to combine, say, an SBA loan with a ROBS down payment, or home equity with personal liquidity. The mix matters because it changes how much debt you carry, how much of your retirement is exposed, and how fast you reach the total investment the brand requires.
            </p>
            <p className="text-white/70 text-sm leading-relaxed">
              The total investment figure you are financing against lives in Item 7 of the brand&apos;s Franchise Disclosure Document. Any financing the franchisor itself offers is in Item 10.
            </p>
          </div>
          <div>
            <h2 className="font-playfair text-2xl text-white mb-4">
              Where Waypoint fits
            </h2>
            <p className="text-white/70 text-sm leading-relaxed mb-4">
              Waypoint does not lend money or earn anything from financing. The consulting is free to you. What we do is help you understand the total capital a given concept actually requires before you fall in love with it, and connect you with funding specialists who handle SBA, ROBS, and the rest.
            </p>
            <p className="text-white/70 text-sm leading-relaxed">
              The goal is simple: no surprises about cost halfway through diligence.
            </p>
            <Link
              href="/investment"
              className="inline-flex items-center text-[#CC6535] text-sm font-medium hover:text-[#D4724A] transition-colors mt-5"
            >
              See how to think about investment level →
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-3xl mx-auto px-6 py-14 sm:py-20">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8E3012] mb-4">
          Common Questions
        </p>
        <h2 className="font-playfair text-2xl sm:text-3xl mb-8">Questions about funding a franchise</h2>
        <div>
          {faqs.map(({ q, a }) => (
            <FAQItem key={q} q={q} a={a} />
          ))}
        </div>
      </section>

      {/* Related resources */}
      <section className="max-w-4xl mx-auto px-6 pb-16 sm:pb-20 border-t border-[#e8e0d0] pt-12">
        <div className="flex items-center gap-4 mb-8">
          <div className="w-8 h-[2px] bg-[#CC6535]" />
          <p className="text-xs font-medium text-[#CC6535] uppercase tracking-[0.2em]">Go Deeper</p>
        </div>
        <div className="grid gap-5 sm:grid-cols-3">
          <Link
            href="/resources/how-franchise-funding-actually-works"
            className="group block bg-white border border-[#e8e0d0] rounded-lg p-5 hover:shadow-md hover:border-[#CC6535]/40 transition-all"
          >
            <p className="text-[0.65rem] font-medium text-[#8E3012] tracking-[0.15em] uppercase mb-3">Going Deeper</p>
            <div className="w-5 h-[2px] bg-[#CC6535] mb-3 group-hover:w-8 transition-all duration-300" />
            <h3 className="font-playfair text-[0.95rem] leading-snug text-[#0c1929] group-hover:text-[#8E3012] transition-colors mb-3">
              How franchise funding actually works
            </h3>
            <p className="text-xs text-[#7a7a6a] leading-relaxed">
              A fuller walk-through of the funding process, from liquidity requirements to lender expectations.
            </p>
            <p className="mt-4 text-xs text-[#8E3012] font-medium tracking-wide">Read →</p>
          </Link>

          <Link
            href="/resources/sba-loan-vs-robs-franchise-funding-comparison"
            className="group block bg-white border border-[#e8e0d0] rounded-lg p-5 hover:shadow-md hover:border-[#CC6535]/40 transition-all"
          >
            <p className="text-[0.65rem] font-medium text-[#8E3012] tracking-[0.15em] uppercase mb-3">Going Deeper</p>
            <div className="w-5 h-[2px] bg-[#CC6535] mb-3 group-hover:w-8 transition-all duration-300" />
            <h3 className="font-playfair text-[0.95rem] leading-snug text-[#0c1929] group-hover:text-[#8E3012] transition-colors mb-3">
              SBA loan vs. ROBS
            </h3>
            <p className="text-xs text-[#7a7a6a] leading-relaxed">
              A side-by-side on the two most common ways people fund a first franchise, and the tradeoffs of each.
            </p>
            <p className="mt-4 text-xs text-[#8E3012] font-medium tracking-wide">Read →</p>
          </Link>

          <Link
            href="/resources/the-true-cost-of-buying-a-franchise"
            className="group block bg-white border border-[#e8e0d0] rounded-lg p-5 hover:shadow-md hover:border-[#CC6535]/40 transition-all"
          >
            <p className="text-[0.65rem] font-medium text-[#8E3012] tracking-[0.15em] uppercase mb-3">Getting Started</p>
            <div className="w-5 h-[2px] bg-[#CC6535] mb-3 group-hover:w-8 transition-all duration-300" />
            <h3 className="font-playfair text-[0.95rem] leading-snug text-[#0c1929] group-hover:text-[#8E3012] transition-colors mb-3">
              The true cost of buying a franchise
            </h3>
            <p className="text-xs text-[#7a7a6a] leading-relaxed">
              Beyond the franchise fee: working capital, build-out, and the reserves you actually need.
            </p>
            <p className="mt-4 text-xs text-[#8E3012] font-medium tracking-wide">Read →</p>
          </Link>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#0c1929] py-14 px-6 text-center">
        <p className="font-playfair text-2xl text-white mb-4">
          Want help mapping the numbers to your situation?
        </p>
        <p className="text-white/70 mb-8 max-w-sm mx-auto text-sm leading-relaxed">
          Thirty minutes. No pitch. We will talk through what concepts fit your capital and how funding usually comes together.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link
            href="/book"
            className="inline-flex items-center justify-center px-8 py-4 text-sm font-semibold tracking-wide text-[#0c1929] bg-[#CC6535] hover:bg-[#D4724A] rounded-lg transition-all min-h-[48px]"
          >
            Book a Free Call
          </Link>
          <a
            href="sms:+12149951062"
            className="inline-flex items-center justify-center gap-1.5 px-8 py-4 text-sm font-semibold tracking-wide text-white border border-white/25 hover:bg-white/10 rounded-lg transition-all min-h-[48px]"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg>
            Text Me
          </a>
        </div>
      </section>
    </main>
  );
}
